/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGuardianThreatFeed,
  IGuardianThreatFeedInterface,
} from "../../../contracts/interfaces/IGuardianThreatFeed";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_query",
        type: "address",
      },
    ],
    name: "isMalicious",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_query",
        type: "string",
      },
    ],
    name: "isMaliciousString",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGuardianThreatFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IGuardianThreatFeedInterface {
    return new Interface(_abi) as IGuardianThreatFeedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGuardianThreatFeed {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGuardianThreatFeed;
  }
}
