/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGuardianRiskAttestation__factory } from "./IGuardianRiskAttestation__factory";
export { IGuardianThreatFeed__factory } from "./IGuardianThreatFeed__factory";
