/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGuardianPassportSBT,
  IGuardianPassportSBTInterface,
} from "../../../../contracts/mocks/PassportTestHelpers.sol/IGuardianPassportSBT";

const _abi = [
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "agentToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_agentHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_score",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_metadataURI",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGuardianPassportSBT__factory {
  static readonly abi = _abi;
  static createInterface(): IGuardianPassportSBTInterface {
    return new Interface(_abi) as IGuardianPassportSBTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGuardianPassportSBT {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IGuardianPassportSBT;
  }
}
