/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  RejectingReceiver,
  RejectingReceiverInterface,
} from "../../../../contracts/mocks/PassportTestHelpers.sol/RejectingReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506101998061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c8063150b7a021461002d575b5f80fd5b61004061003b3660046100d0565b61005d565b6040516001600160e01b0319909116815260200160405180910390f35b60405162461bcd60e51b815260206004820152602160248201527f52656a656374696e6752656365697665723a20746f6b656e2072656a656374656044820152601960fa1b60648201525f9060840160405180910390fd5b80356001600160a01b03811681146100cb575f80fd5b919050565b5f805f805f608086880312156100e4575f80fd5b6100ed866100b5565b94506100fb602087016100b5565b935060408601359250606086013567ffffffffffffffff8082111561011e575f80fd5b818801915088601f830112610131575f80fd5b81358181111561013f575f80fd5b896020828501011115610150575f80fd5b969995985093965060200194939250505056fea26469706673582212200982ee42ed8973c496e41c52c5d52fb51a8f3d50e0dae9ea670709a519445fdf64736f6c63430008180033";

type RejectingReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RejectingReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RejectingReceiver__factory extends ContractFactory {
  constructor(...args: RejectingReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RejectingReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RejectingReceiver__factory {
    return super.connect(runner) as RejectingReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RejectingReceiverInterface {
    return new Interface(_abi) as RejectingReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RejectingReceiver {
    return new Contract(address, _abi, runner) as unknown as RejectingReceiver;
  }
}
