/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace GuardianInterlockRegistry {
  export type InterlockProofStruct = {
    agentA: BytesLike;
    agentB: BytesLike;
    proofHash: BytesLike;
    nonce: BigNumberish;
    registeredAt: BigNumberish;
    revoked: boolean;
  };

  export type InterlockProofStructOutput = [
    agentA: string,
    agentB: string,
    proofHash: string,
    nonce: bigint,
    registeredAt: bigint,
    revoked: boolean
  ] & {
    agentA: string;
    agentB: string;
    proofHash: string;
    nonce: bigint;
    registeredAt: bigint;
    revoked: boolean;
  };
}

export interface GuardianInterlockRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_INTERLOCKS"
      | "acceptOwnership"
      | "getInterlock"
      | "getInterlockCount"
      | "interlockIds"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "registerInterlock"
      | "registry"
      | "renounceOwnership"
      | "revokeInterlock"
      | "transferOwnership"
      | "unpause"
      | "verifyInterlock"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InterlockRegistered"
      | "InterlockRevoked"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_INTERLOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInterlock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInterlockCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interlockIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerInterlock",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeInterlock",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyInterlock",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_INTERLOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterlockCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "interlockIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerInterlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeInterlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyInterlock",
    data: BytesLike
  ): Result;
}

export namespace InterlockRegisteredEvent {
  export type InputTuple = [
    interlockId: BytesLike,
    agentA: BytesLike,
    agentB: BytesLike,
    proofHash: BytesLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    interlockId: string,
    agentA: string,
    agentB: string,
    proofHash: string,
    nonce: bigint
  ];
  export interface OutputObject {
    interlockId: string;
    agentA: string;
    agentB: string;
    proofHash: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterlockRevokedEvent {
  export type InputTuple = [interlockId: BytesLike];
  export type OutputTuple = [interlockId: string];
  export interface OutputObject {
    interlockId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GuardianInterlockRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GuardianInterlockRegistry;
  waitForDeployment(): Promise<this>;

  interface: GuardianInterlockRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_INTERLOCKS: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  getInterlock: TypedContractMethod<
    [_interlockId: BytesLike],
    [GuardianInterlockRegistry.InterlockProofStructOutput],
    "view"
  >;

  getInterlockCount: TypedContractMethod<[], [bigint], "view">;

  interlockIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  registerInterlock: TypedContractMethod<
    [
      _agentA: BytesLike,
      _agentB: BytesLike,
      _proofHash: BytesLike,
      _nonce: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  registry: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        agentA: string;
        agentB: string;
        proofHash: string;
        nonce: bigint;
        registeredAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeInterlock: TypedContractMethod<
    [_interlockId: BytesLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  verifyInterlock: TypedContractMethod<
    [_interlockId: BytesLike],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_INTERLOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getInterlock"
  ): TypedContractMethod<
    [_interlockId: BytesLike],
    [GuardianInterlockRegistry.InterlockProofStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInterlockCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "interlockIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerInterlock"
  ): TypedContractMethod<
    [
      _agentA: BytesLike,
      _agentB: BytesLike,
      _proofHash: BytesLike,
      _nonce: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, boolean] & {
        agentA: string;
        agentB: string;
        proofHash: string;
        nonce: bigint;
        registeredAt: bigint;
        revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeInterlock"
  ): TypedContractMethod<[_interlockId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyInterlock"
  ): TypedContractMethod<[_interlockId: BytesLike], [string], "view">;

  getEvent(
    key: "InterlockRegistered"
  ): TypedContractEvent<
    InterlockRegisteredEvent.InputTuple,
    InterlockRegisteredEvent.OutputTuple,
    InterlockRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InterlockRevoked"
  ): TypedContractEvent<
    InterlockRevokedEvent.InputTuple,
    InterlockRevokedEvent.OutputTuple,
    InterlockRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "InterlockRegistered(bytes32,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      InterlockRegisteredEvent.InputTuple,
      InterlockRegisteredEvent.OutputTuple,
      InterlockRegisteredEvent.OutputObject
    >;
    InterlockRegistered: TypedContractEvent<
      InterlockRegisteredEvent.InputTuple,
      InterlockRegisteredEvent.OutputTuple,
      InterlockRegisteredEvent.OutputObject
    >;

    "InterlockRevoked(bytes32)": TypedContractEvent<
      InterlockRevokedEvent.InputTuple,
      InterlockRevokedEvent.OutputTuple,
      InterlockRevokedEvent.OutputObject
    >;
    InterlockRevoked: TypedContractEvent<
      InterlockRevokedEvent.InputTuple,
      InterlockRevokedEvent.OutputTuple,
      InterlockRevokedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
