/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GuardianCircuitBreakerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "circuitBreakerActive"
      | "circuitBreakerAdmin"
      | "riskAttestation"
      | "riskScoreThreshold"
      | "setCircuitBreakerActive"
      | "setRiskScoreThreshold"
      | "threatFeed"
      | "transferCircuitBreakerAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CircuitBreakerAdminTransferred"
      | "CircuitBreakerToggled"
      | "RiskThresholdUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "circuitBreakerActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circuitBreakerAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskAttestation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskScoreThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCircuitBreakerActive",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskScoreThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "threatFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferCircuitBreakerAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "circuitBreakerActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "circuitBreakerAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskScoreThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCircuitBreakerActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskScoreThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threatFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferCircuitBreakerAdmin",
    data: BytesLike
  ): Result;
}

export namespace CircuitBreakerAdminTransferredEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CircuitBreakerToggledEvent {
  export type InputTuple = [active: boolean];
  export type OutputTuple = [active: boolean];
  export interface OutputObject {
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GuardianCircuitBreaker extends BaseContract {
  connect(runner?: ContractRunner | null): GuardianCircuitBreaker;
  waitForDeployment(): Promise<this>;

  interface: GuardianCircuitBreakerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  circuitBreakerActive: TypedContractMethod<[], [boolean], "view">;

  circuitBreakerAdmin: TypedContractMethod<[], [string], "view">;

  riskAttestation: TypedContractMethod<[], [string], "view">;

  riskScoreThreshold: TypedContractMethod<[], [bigint], "view">;

  setCircuitBreakerActive: TypedContractMethod<
    [_active: boolean],
    [void],
    "nonpayable"
  >;

  setRiskScoreThreshold: TypedContractMethod<
    [_threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  threatFeed: TypedContractMethod<[], [string], "view">;

  transferCircuitBreakerAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "circuitBreakerActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "circuitBreakerAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "riskAttestation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "riskScoreThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setCircuitBreakerActive"
  ): TypedContractMethod<[_active: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRiskScoreThreshold"
  ): TypedContractMethod<[_threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "threatFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferCircuitBreakerAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CircuitBreakerAdminTransferred"
  ): TypedContractEvent<
    CircuitBreakerAdminTransferredEvent.InputTuple,
    CircuitBreakerAdminTransferredEvent.OutputTuple,
    CircuitBreakerAdminTransferredEvent.OutputObject
  >;
  getEvent(
    key: "CircuitBreakerToggled"
  ): TypedContractEvent<
    CircuitBreakerToggledEvent.InputTuple,
    CircuitBreakerToggledEvent.OutputTuple,
    CircuitBreakerToggledEvent.OutputObject
  >;
  getEvent(
    key: "RiskThresholdUpdated"
  ): TypedContractEvent<
    RiskThresholdUpdatedEvent.InputTuple,
    RiskThresholdUpdatedEvent.OutputTuple,
    RiskThresholdUpdatedEvent.OutputObject
  >;

  filters: {
    "CircuitBreakerAdminTransferred(address,address)": TypedContractEvent<
      CircuitBreakerAdminTransferredEvent.InputTuple,
      CircuitBreakerAdminTransferredEvent.OutputTuple,
      CircuitBreakerAdminTransferredEvent.OutputObject
    >;
    CircuitBreakerAdminTransferred: TypedContractEvent<
      CircuitBreakerAdminTransferredEvent.InputTuple,
      CircuitBreakerAdminTransferredEvent.OutputTuple,
      CircuitBreakerAdminTransferredEvent.OutputObject
    >;

    "CircuitBreakerToggled(bool)": TypedContractEvent<
      CircuitBreakerToggledEvent.InputTuple,
      CircuitBreakerToggledEvent.OutputTuple,
      CircuitBreakerToggledEvent.OutputObject
    >;
    CircuitBreakerToggled: TypedContractEvent<
      CircuitBreakerToggledEvent.InputTuple,
      CircuitBreakerToggledEvent.OutputTuple,
      CircuitBreakerToggledEvent.OutputObject
    >;

    "RiskThresholdUpdated(uint16,uint16)": TypedContractEvent<
      RiskThresholdUpdatedEvent.InputTuple,
      RiskThresholdUpdatedEvent.OutputTuple,
      RiskThresholdUpdatedEvent.OutputObject
    >;
    RiskThresholdUpdated: TypedContractEvent<
      RiskThresholdUpdatedEvent.InputTuple,
      RiskThresholdUpdatedEvent.OutputTuple,
      RiskThresholdUpdatedEvent.OutputObject
    >;
  };
}
