/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MockDependencies {
  export type AttestationStruct = {
    score: BigNumberish;
    grade: string;
    signalsHash: BytesLike;
    attestedAt: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type AttestationStructOutput = [
    score: bigint,
    grade: string,
    signalsHash: string,
    attestedAt: bigint,
    blockNumber: bigint
  ] & {
    score: bigint;
    grade: string;
    signalsHash: string;
    attestedAt: bigint;
    blockNumber: bigint;
  };
}

export interface MockDependenciesInterface extends Interface {
  getFunction(
    nameOrSignature: "getAttestation" | "isMalicious" | "isMaliciousString"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isMalicious",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMaliciousString",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMalicious",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMaliciousString",
    data: BytesLike
  ): Result;
}

export interface MockDependencies extends BaseContract {
  connect(runner?: ContractRunner | null): MockDependencies;
  waitForDeployment(): Promise<this>;

  interface: MockDependenciesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAttestation: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [MockDependencies.AttestationStructOutput],
    "view"
  >;

  isMalicious: TypedContractMethod<
    [arg0: AddressLike],
    [[boolean, string]],
    "view"
  >;

  isMaliciousString: TypedContractMethod<
    [arg0: string],
    [[boolean, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [MockDependencies.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMalicious"
  ): TypedContractMethod<[arg0: AddressLike], [[boolean, string]], "view">;
  getFunction(
    nameOrSignature: "isMaliciousString"
  ): TypedContractMethod<[arg0: string], [[boolean, string]], "view">;

  filters: {};
}
