/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGuardianThreatFeedInterface extends Interface {
  getFunction(
    nameOrSignature: "isMalicious" | "isMaliciousString"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isMalicious",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMaliciousString",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isMalicious",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMaliciousString",
    data: BytesLike
  ): Result;
}

export interface IGuardianThreatFeed extends BaseContract {
  connect(runner?: ContractRunner | null): IGuardianThreatFeed;
  waitForDeployment(): Promise<this>;

  interface: IGuardianThreatFeedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isMalicious: TypedContractMethod<
    [_query: AddressLike],
    [[boolean, string]],
    "view"
  >;

  isMaliciousString: TypedContractMethod<
    [_query: string],
    [[boolean, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isMalicious"
  ): TypedContractMethod<[_query: AddressLike], [[boolean, string]], "view">;
  getFunction(
    nameOrSignature: "isMaliciousString"
  ): TypedContractMethod<[_query: string], [[boolean, string]], "view">;

  filters: {};
}
