/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IGuardianRiskAttestation {
  export type AttestationStruct = {
    score: BigNumberish;
    grade: string;
    signalsHash: BytesLike;
    attestedAt: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type AttestationStructOutput = [
    score: bigint,
    grade: string,
    signalsHash: string,
    attestedAt: bigint,
    blockNumber: bigint
  ] & {
    score: bigint;
    grade: string;
    signalsHash: string;
    attestedAt: bigint;
    blockNumber: bigint;
  };
}

export interface IGuardianRiskAttestationInterface extends Interface {
  getFunction(nameOrSignature: "getAttestation"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
}

export interface IGuardianRiskAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): IGuardianRiskAttestation;
  waitForDeployment(): Promise<this>;

  interface: IGuardianRiskAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAttestation: TypedContractMethod<
    [_contractAddress: AddressLike, _chain: string],
    [IGuardianRiskAttestation.AttestationStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [_contractAddress: AddressLike, _chain: string],
    [IGuardianRiskAttestation.AttestationStructOutput],
    "view"
  >;

  filters: {};
}
