/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as passportTestHelpersSol from "./PassportTestHelpers.sol";
export type { passportTestHelpersSol };
export type { MockERC20 } from "./MockERC20";
