"""One-shot sync of WHITEPAPER.md audit corrections into WHITEPAPER_PUBLIC.md.
Run from repo root: python tools/sync_public_whitepaper.py
Reports applied/missed per replacement so nothing silently fails."""
import io

p = "WHITEPAPER_PUBLIC.md"
s = io.open(p, encoding="utf-8").read()

pairs = []

pairs.append((
    "- **Layer 2 \u2014 On-Chain Web3 Trust:** Six EVM-compatible smart contracts (Monad/Base) provide cryptographically verifiable AI identity, decentralized authorization, automated liability, and a built-in smart contract static analyzer to audit the very contracts GuardianAI deploys.",
    "- **Layer 2 \u2014 On-Chain Web3 Trust:** Nine EVM-compatible smart contracts (Monad/Base) provide cryptographically verifiable AI identity, decentralized authorization, certificate anchoring, and a built-in smart contract static analyzer to audit the very contracts GuardianAI deploys. Agent identities are additionally registered on the canonical ERC-8004 \"Trustless Agents\" registries with transient registrar custody and client ownership handoff (Feature 39).",
))

pairs.append((
    "\u2502  \u2022 InsuranceLedger (SLA/Stake)   \u2502",
    "\u2502  \u2022 InsuranceLedger (Certificates)\u2502\n                        \u2502  \u2022 + ERC-8004 canonical registries \u2502",
))

pairs.append((
    "Combines Slither AST/CFG structural analysis with custom semantic detectors to identify **52 distinct vulnerability classes** across Solidity and Vyper.",
    "Combines Slither AST/CFG structural analysis with custom semantic detectors covering **48 implemented rule IDs** across Solidity and Vyper.",
))

analyzer_old = ("Specifically, the SOC-2 and ISO 27001 compliance mappings generated by this tool "
                "cannot currently be relied upon for formal certification evidence, as the underlying "
                "detections do not reliably distinguish between vulnerable and safe code.")
analyzer_new = analyzer_old + ("\n\n**Status update (August 2026):** the codebase now integrates a real AST layer "
    "\u2014 `audit/slither_engine.py` (Slither 0.11.x, pinned) and `audit/vyper_engine.py` feed AST-validated "
    "findings into the analyzer, with approximately 30 of the rule IDs routed through Slither/Vyper "
    "structural validation (`is_slither_targeted`). The July 2026 \"regex-only\" characterization above is "
    "retained as the historical audit record; the headline counts in this section have been corrected to "
    "the implemented figure (48 rule IDs, not 52). A fresh empirical false-positive re-run against the "
    "July audit's 18-class benchmark has not yet been published \u2014 treat analyzer output as improved but "
    "not yet independently validated.")
pairs.append((analyzer_old, analyzer_new))

pairs.append((
    "Six EVM-compatible smart contracts deployed on Monad/Base provide cryptographic truth about GuardianAI's operational state.",
    "Nine GuardianAI contracts are deployed on Monad/Base \u2014 the six registries below plus GuardianTimelock, "
    "GuardianCircuitBreaker, and GuardianProtectedVault \u2014 providing cryptographic truth about GuardianAI's "
    "operational state. Agent identities are additionally registered on the **canonical ERC-8004 \"Trustless "
    "Agents\" registries** (Feature 39), which GuardianAI does not deploy or own.",
))

f36_old = ("**Feature 36 \u2014 GuardianInsuranceLedger (Automated Liability)**\n\n"
    "A smart contract that holds a deployer stake. If an AI agent cryptographically violates a defined SLA "
    "\u2014 proven via the CortexAnchor's immutable log \u2014 the contract slashes the stake or triggers a payout "
    "to the affected party.\n\n"
    "- **What it does:** Converts abstract \"AI liability\" into a programmable, mathematically enforced "
    "financial instrument. No human adjudication needed.\n"
    "- **Why it matters:** Makes the cost of deploying an unsafe AI agent quantifiable and automatic, "
    "creating genuine accountability for deployers.\n"
    "- **What it is in code:** `cortex/insurance.py`, `contracts/GuardianInsuranceLedger.sol`.")
f36_new = ("**Feature 36 \u2014 GuardianInsuranceLedger (Insurance Certificate Anchoring)**\n\n"
    "> **Correction (August 2026):** earlier revisions described this contract as holding a deployer stake "
    "with automated slashing and payouts. **That functionality was never implemented.** The description "
    "below reflects what the deployed contract actually does.\n\n"
    "An on-chain registry that anchors signed insurance certificates for AI agents, storing integrity hashes "
    "and validity periods so third parties can verify an agent's insurance status.\n\n"
    "- **What it does:** issues and revokes certificate records (`agentHash`, period start/end, `certHash`, "
    "risk level) with owner-gated writes, reentrancy protection, pausability, pagination for off-chain "
    "enumeration, and a 100,000-certificate cap. No ETH is held or moved; the contract is not payable.\n"
    "- **Why it matters:** verifiable insurance posture becomes a queryable on-chain fact rather than a PDF "
    "in someone's inbox.\n"
    "- **Honest scope:** there is no stake, no slashing, and no automated payout path at any layer "
    "(`contracts/GuardianInsuranceLedger.sol` and `cortex/insurance.py`). Automated liability remains a design "
    "direction: the intended shape is a downstream service consuming ERC-8004 Reputation/Validation data "
    "(Feature 39) as breach evidence \u2014 not a registry itself. The live AI-insurance market currently operates "
    "off-chain (e.g., Lloyd's-backed coverholders); no on-chain agent-liability product has demonstrated demand.\n"
    "- **What it is in code:** `cortex/insurance.py` (certificate builder), `contracts/GuardianInsuranceLedger.sol`.")
pairs.append((f36_old, f36_new))

f38_anchor = "- **What it is in code:** `audit/onchain_risk_scorer.py`, `contracts/GuardianRiskAttestation.sol`."
f39_block = f38_anchor + ("""

---

**Feature 39 \u2014 ERC-8004 Identity Registration (Canonical Trustless Agents)**

> Added August 2026. GuardianAI registers protected agents on the **canonical** ERC-8004 Identity Registry
> (`0x8004A169\u2026a432`, deterministic CREATE2 deployment shared across chains) instead of operating a competing identity standard.

- **What it does:** for each opted-in agent, GuardianAI calls `register()` on the canonical registry, writes
  `setMetadata(agentId, "guardianPassportId", <passport id>)` linking the standard identity to the
  GuardianPassportSBT credential, serves the spec-compliant registration JSON at
  `/api/v1/erc8004/agents/{agent_id}.json`, and \u2014 when a client owner address is supplied \u2014 hands full NFT
  ownership to the client via `transferFrom`.
- **Ownership policy (register-then-transfer):** transient registrar custody only. Transfer happens *after*
  setMetadata because only the current owner can write metadata. Absent an owner address, the identity stays
  custodial and the queue row says so explicitly.
- **Safety design:** fail-closed `eth_getCode` verification before first send per chain; production-URI gate
  refusing localhost/non-https `GUARDIAN_PUBLIC_URL` on mainnet chains; gas-price ceiling reuse; daily on-chain
  spend budget; idempotent retries (broadcast-hash preservation + receipt recovery prevents double mints);
  conditional-claim row locking against concurrent workers; chain rollout base-sepolia \u2192 base \u2192 monad-testnet.
- **Honest scope:** discovery-only today \u2014 no Reputation emission and no Validation-Registry validator yet
  (the Validation portion of ERC-8004 is still marked unstable by its editors). Default disabled behind
  `GUARDIAN_ERC8004_ENABLED=false`; nothing changes at runtime until enabled.
- **What it is in code:** `guardian/passport/erc8004_registrar.py`,
  `backend/routers/identity_registry_routes.py`, hook in `passport_core.issue_passport()`;
  tests `tests/web3_identity/` (42 tests, offline fakes + failure injection).""")
pairs.append((f38_anchor, f39_block))

pairs.append((
    "  English-language prompts bypass the translation step entirely (zero latency penalty for the majority of traffic).",
    "  English-language prompts bypass the translation step entirely (zero latency penalty for the majority of traffic).\n\n"
    "- **Deployment disclosure (August 2026):** translation uses a third-party service (Google Translate's free "
    "endpoint), so **raw non-English prompts transit an external service before filtering**. Deployments with "
    "strict data-sovereignty requirements should either restrict ingress to English or front the adapter with an "
    "approved enterprise translation endpoint.",
))

pairs.append((
    "Verified results: 95.68 rps (safe load), 494.01 rps block throughput (attack load), 100% block rate under "
    "adversarial concurrent load, 41.88 ms p95 attack latency. Source: `artifacts/performance/perf_chaos_report.json` (2026-08-08).",
    "Verified results (from `artifacts/performance/perf_chaos_report.json`, last regenerated June 2026 \u2014 **a "
    "120-request harness; enterprise-scale rerun is open backlog**): 95.68 rps (safe load), 494.01 rps block "
    "throughput (attack load), 100% block rate under adversarial concurrent load, 41.88 ms p95 attack latency.",
))

pairs.append((
    "2. Audits Solidity/Vyper contracts with 52 verified vulnerability rules before deployment.",
    "2. Audits Solidity/Vyper contracts with 48 static-analysis rule IDs (high-severity subset AST-validated via "
    "Slither/Vyper) before deployment.",
))

applied, missed = 0, []
for old, new in pairs:
    if old in s:
        s = s.replace(old, new, 1)
        applied += 1
    else:
        missed.append(old[:70])

io.open(p, "w", encoding="utf-8", newline="\n").write(s)
print(f"applied {applied}/{len(pairs)}")
for m in missed:
    print("MISS:", m)
